---
name: pre-commit action
description: "Run pre-commit hooks on your repository"
runs:
  using: composite
  steps:
    - name: Set up Homebrew
      id: setup-homebrew
      uses: Homebrew/actions/setup-homebrew@master
      with:
        core: false
        cask: false
        test-bot: false
    - name: Set up actionlint
      env:
        HOMEBREW_REPOSITORY: ${{ steps.setup-homebrew.outputs.repository-path }}
      run: |
        brew install suzuki-shunsuke/ghalint/ghalint
      shell: bash
    - name: pre-commit
      uses: pre-commit/action@v3.0.1
    - name: common pre-commit
      uses: pre-commit/action@v3.0.1
      with:
        extra_args: --all-files --config ${{ github.workspace }}/.github/actions/composite-actions/pre-commit/.pre-commit-config.yaml
