---
name: pre-commit action
description: "Run pre-commit hooks on your repository"
runs:
  using: composite
  steps:
    - name: pre-commit
      uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
    - name: common pre-commit
      uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
      with:
        extra_args: --all-files --config ${{ github.workspace }}/.github/actions/composite-actions/pre-commit/.pre-commit-config.yaml
