---
name: setup-node
description: Set up Node.js
inputs:
  working-directory:
    description: "The working directory to run the setup-node action in"
    required: false
    default: .
runs:
  using: composite
  steps:
    - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
      with:
        node-version-file: ${{ inputs.working-directory }}/.node-version
        cache: "npm"
        cache-dependency-path: ${{ inputs.working-directory }}/package-lock.json
    - name: Install dependencies
      run: npm ci
      working-directory: ${{ inputs.working-directory }}
      shell: bash
