---
name: setup-node
description: Set up Node.js
inputs:
  working-directory:
    description: "The working directory to run the setup-node action in"
    required: false
    default: .
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.woking-directory }}/.node-version
        cache-dependency-path: ${{ inputs.woking-directory }}/package-lock.json
    - name: Install dependencies
      run: npm ci
      working-directory: ${{ inputs.working-directory }}
      shell: bash
