---
name: setup-node
description: Set up Node.js
inputs:
  working-directory:
    description: "The working directory to run the setup-node action in"
    required: false
    default: .
runs:
  using: composite
  steps:
    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version-file: ${{ inputs.working-directory }}/.node-version
        cache: "npm"
        cache-dependency-path: ${{ inputs.working-directory }}/package-lock.json
    - name: Install dependencies
      run: npm ci
      working-directory: ${{ inputs.working-directory }}
      shell: bash
