---
name: npm publish
description: Publish an npm package
inputs:
  npm-token:
    description: "NPM token"
    required: true
runs:
  using: composite
  steps:
    - name: Read version from package.json
      id: read_version
      run: |
        version=$(jq -r '.version' package.json)
        echo "PACKAGE_VERSION=$version" >> $GITHUB_ENV
      shell: bash
    - name: Check if tag already exists
      id: check_tag
      run: |
        if git rev-parse "v${PACKAGE_VERSION}" >/dev/null 2>&1; then
          echo "Tag v${PACKAGE_VERSION} already exists."
          exit 1
        fi
      shell: bash
    - name: Create a new tag
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git tag -a "v${PACKAGE_VERSION}" -m "Release v${PACKAGE_VERSION}"
        git push origin "v${PACKAGE_VERSION}"
      env:
        PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}
      shell: bash
    - uses: JS-DevTools/npm-publish@v3
      id: publish
      with:
        token: ${{ inputs.npm-token }}
