---
name: npm publish
description: Publish an npm package
inputs:
  npm-token:
    description: "NPM token"
    required: true
runs:
  using: composite
  steps:
    - name: Read version from package.json
      id: read_version
      run: |
        version=$(jq -r '.version' package.json)
        echo "PACKAGE_VERSION=$version" >> $GITHUB_ENV
      shell: bash
    - uses: mukunku/tag-exists-action@5c39604fe8aef7e65acb6fbcf96ec580f7680313 # v1.7.0
      id: check-tag
      with:
        tag: ${{ env.PACKAGE_VERSION }}
    - uses: JS-DevTools/npm-publish@19c28f1ef146469e409470805ea4279d47c3d35c # v3
      if: steps.check-tag.outputs.exists == 'false'
      id: publish
      with:
        token: ${{ inputs.npm-token }}
    - name: Create a new tag
      if: steps.publish.outcome == 'success'
      uses: EndBug/latest-tag@7589411ebda7bc8f98deb2dbc37e3dc45828f7d0 # v1
      with:
        ref: ${{ env.PACKAGE_VERSION }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
