---
name: npm publish
description: Publish an npm package
inputs:
  npm-token:
    description: "NPM token"
    required: true
runs:
  using: composite
  steps:
    - name: Read version from package.json
      id: read_version
      run: |
        version=$(jq -r '.version' package.json)
        echo "PACKAGE_VERSION=$version" >> $GITHUB_ENV
      shell: bash
    - uses: mukunku/tag-exists-action@v1.6.0
      id: check-tag
      with:
        tag: ${{ env.PACKAGE_VERSION }}
    - name: Create a new tag
      if: steps.check-tag.outputs.exists == 'false'
      uses: EndBug/latest-tag@v1
      with:
        ref: ${{ env.PACKAGE_VERSION }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - uses: JS-DevTools/npm-publish@v3
      if: steps.check-tag.outputs.exists == 'false'
      id: publish
      with:
        token: ${{ inputs.npm-token }}
