---
name: check-pr
description: Check if the PR is a Renovate PR
outputs:
  is-renovate-pr:
    description: "Set to true if the PR is a Renovate PR"
    value: ${{ steps.check-pr.outputs.is-renovate }}
runs:
  using: composite
  steps:
    - name: Check if the PR is a Renovate PR
      id: check-pr
      run: |
        PR_AUTHOR=$(jq -r '.pull_request.user.login' "$GITHUB_EVENT_PATH")
        if [ "$PR_AUTHOR" == "renovate[bot]" ]; then
          echo "This PR is created by Renovate. \
          Skipping the build and upload steps."
          echo "is-renovate=true" >> $GITHUB_OUTPUT
        else
          echo "This PR is not created by Renovate."
          echo "is-renovate=false" >> $GITHUB_OUTPUT
        fi
      shell: bash
