---
name: add-tag-from-package
description: Add a tag from the package.json version
runs:
  using: composite
  steps:
    - name: Read version from package.json
      id: read_version
      run: |
        version=$(jq -r '.version' package.json)
        echo "PACKAGE_VERSION=$version" >> $GITHUB_ENV
      shell: bash
    - uses: mukunku/tag-exists-action@bdad1eaa119ce71b150b952c97351c75025c06a9 # v1.6.0
      id: check-tag
      with:
        tag: ${{ env.PACKAGE_VERSION }}
    - name: Create a new tag
      if: steps.check-tag.outputs.exists == 'false'
      uses: EndBug/latest-tag@7589411ebda7bc8f98deb2dbc37e3dc45828f7d0 # v1
      with:
        ref: ${{ env.PACKAGE_VERSION }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
